[project]
name = 'stacks-dao'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.dao-adapter-v1]
path = 'contracts/traits/dao-adapter.trait'
clarity_version = 4
epoch = 'latest'

[contracts.dao-core-v1]
path = 'contracts/dao-core.clar'
clarity_version = 4
epoch = 'latest'

[contracts.dao-treasury-v1]
path = 'contracts/dao-treasury.clar'
clarity_version = 4
epoch = 'latest'

[contracts.token-trait-v1]
path = 'contracts/traits/token.trait'
clarity_version = 4
epoch = 'latest'

[contracts.transfer-adapter-v1]
path = 'contracts/adapters/transfer-adapter.clar'
clarity_version = 4
epoch = 'latest'

[contracts.treasury-trait-v1]
path = 'contracts/traits/treasury.trait'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
